### ISSUE TITLE
As a developer, I would like to create a database so that components can be developed independently based on a common data model.

### ISSUE THREAD

**Issue by OnurDz** [SleeplessKnigts/donence-android#6]

**Comment by MArifSahin** [comment]
CREATE TABLE IF NOT EXISTS "cloud_roles"
(
    role_id SERIAL PRIMARY KEY,
    role    VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS cloud_users
(
    id             INT PRIMARY KEY,
    username       TEXT UNIQUE,
    email          TEXT NOT NULL UNIQUE,
    auth_provider  TEXT NOT NULL,
    image_url      TEXT,
    f_name         TEXT,
    address        POINT,
    address_detail TEXT,
    role_id        INT  NOT NULL REFERENCES cloud_roles (role_id)
);

CREATE TABLE IF NOT EXISTS "recycle_points"
(
    recycle_point_id     SERIAL PRIMARY KEY,
    recycle_point_detail TEXT NOT NULL,
    geolocation          POINT
);

CREATE TABLE IF NOT EXISTS "news"
(
    news_id   SERIAL PRIMARY KEY,
    heading   TEXT    NOT NULL,
    published BOOLEAN NOT NULL DEFAULT FALSE,
    content   TEXT    NOT NULL
);

CREATE TABLE IF NOT EXISTS "recycling_numbers"
(
    recycling_numbers_id SERIAL PRIMARY KEY,
    glass                INT DEFAULT 0,
    paper                INT DEFAULT 0,
    cardboard            INT DEFAULT 0,
    metal                INT DEFAULT 0,
    plastic              INT DEFAULT 0,
    battery              INT DEFAULT 0,
    user_id              INT NOT NULL REFERENCES cloud_users (id)
);

CREATE TABLE IF NOT EXISTS "collection_events"
(
    collection_events_id SERIAL PRIMARY KEY,
    material_type        TEXT                        NOT NULL,
    event_detail         TEXT                        NOT NULL,
    geolocation          POINT,
    event_date           TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

INSERT INTO cloud_roles (role)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS(SELECT * FROM cloud_roles WHERE role = 'ROLE_ADMIN');
INSERT INTO cloud_roles (role)
SELECT 'ROLE_DRIVER'
WHERE NOT EXISTS(SELECT * FROM cloud_roles WHERE role = 'ROLE_DRIVER');
INSERT INTO cloud_roles (role)
SELECT 'ROLE_USER'
WHERE NOT EXISTS(SELECT * FROM cloud_roles WHERE role = 'ROLE_USER');

INSERT INTO cloud_users (id, username, email, auth_provider, image_url, f_name, role_id)
VALUES (1, 'donence', 'donence.dev@gmail.com', 'google',
        'https://lh3.googleusercontent.com/-8BfZWq4QlAE/AAAAAAAAAAI/AAAAAAAAAAA/AMZuuckbqhUpbJmuXqImD5Fi-Pv38Emxjw/s96-c/photo.jpg',
        'Donence Donence', 1);

INSERT INTO news (news_id, heading, published, content)
VALUES (1, 'Heading', 'true',
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');

INSERT INTO collection_events (collection_events_id, material_type, event_detail, geolocation, event_date)
VALUES (1, 'cardboard', 'Collection event 1', '(39.904239006864785, 32.87195490942385)', '2021-03-01 19:10:25-07');

INSERT INTO recycle_points(recycle_point_detail, geolocation)
VALUES ('Example recycle point', '(39.904239006864785, 32.87195490942385)');

INSERT INTO recycling_numbers(glass, paper, cardboard, metal, plastic, battery, user_id)
VALUES (0, 1, 5, 1, 3, 2, 1);
